#!/usr/bin/env python
# -*- coding: utf-8 -*-
import pickle
import datetime
#modelo Filas x Columnas
encabezado={
    "nombre":'comporbante',
    "tampapel":{'ancho': 8.5, 'alto': 11, 'medida': 'pul'},
    "pagup":{'up': (1, 1), 'uporden': 'Z'},
    "tipos":(('Ubuntu', 'Ubuntu-R.ttf'), ('Ubuntu-Bold', 'Ubuntu-B.ttf'), 
             ('Ubuntu-Cond', 'Ubuntu-C.ttf'), ('f2sCodigo128', 'Codigo128.ttf')),
    "formato":'comporbante.png',
    "modo":1,
    "saltopag":('\x0c',),
    "nolineablanco":True,
    "eliminartexto":('\x1bP', 
                     '\x1bM', '+----------+-----+-----------------+-------------------+-------------------+-------------------+', 
                     '+------------------------------------------------------+-------------------+-------------------+', 
                     '|---------------------------------------+--------------------+=================|', 
                     '|          |     |                 |                   |                   |                   |', 
                     '|  Cuenta  | C.O | Tercero         | Dcto_Cruce/Provee.|   D e b i t o s   |  C r e d i t o s  |'),
    "detallefijo":{'inicio': '[ CONTABILIZACION ]', 'fin': 'SUMAS IGUALES', 
                   'pasa': '* P A S A *', 'viene': '* V I E N E *', 
                   'lineas': 26, 'largoEncabezado': 43},
    "moverlineas":({'buscartexto': '[ EGRESO DE BANCOS ]', 'nuevafila': 20}, 
                   {'buscartexto': 'T O T A L', 'nuevafila': 36}),
    "saltolineadoc":1,
    "nombre_pdf":{'selector': [{'fila': 3, 'columnas': (67, 80)}], 
                  'formato': 'comporbante-{}', 
                  'ruta_pdf': '/home/www-data/web2py/applications/siendo/static/PDF'},
    "agrupar":{'fila': 3, 'columnas': (67, 80)},
    "correoweb2py":[{'fila': 3, 'columnas': (67, 80), 'nombre': 'nrodoc'}, 
                    {'fila': 7, 'columnas': (16, 53), 'nombre': 'nombre'}, 
                    {'fila': 7, 'columnas': (62, 80), 'nombre': 'nit', 'hasta': '-'}, 
                    {'fila': 4, 'columnas': (67, 80), 'nombre': 'Fecha', 'convert': 'fecha1'}, 
                    {"fila":11, "columnas":(63,80),   "nombre":"valor","convert":"float"}, 
                ]
    }
selector=[
          { 'fila':3,
            'nombre':'Numero',
            'columnas':(67, 80),
            'letra':'Ubuntu-Bold',
            'letra_alto':12,
            'posx':468,
            'posy':731,
            'alinear':'I',
            'desp_y':0,
            'desp_x':0,
          },
          { 'fila':4,
            'nombre':'Fecha',
            'columnas':(67, 80),
            'letra':'Ubuntu-Bold',
            'letra_alto':10,
            'posx':468,
            'posy':717,
            'alinear':'I',
            'desp_y':0,
            'desp_x':0,
          },
          { 'fila':7,
            'nombre':'Entregado a',
            'columnas':(16, 53),
            'letra':'Ubuntu-Bold',
            'letra_alto':10,
            'posx':97,
            'posy':669,
            'alinear':'I',
            'desp_y':0,
            'desp_x':0,
          },
          { 'fila':7,
            'nombre':'Nit o CC',
            'columnas':(62, 80),
            'letra':'Ubuntu-Bold',
            'letra_alto':10,
            'posx':444,
            'posy':669,
            'alinear':'I',
            'desp_y':0,
            'desp_x':0,
          },
          {'filas':(8, 9),
            'nombre':'la suma de',
            'columnas':(16, 80),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':96,
            'posy':651,
            'desp_y':15,
            'alinear':'I',
            'desp_x':0,
          },
          { 'fila':11,
            'nombre':'entregado valor',
            'columnas':(63, 80),
            'letra':'Ubuntu-Bold',
            'letra_alto':10,
            'posx':527,
            'posy':605,
            'alinear':'D',
            'desp_y':0,
            'desp_x':0,
          },
          ##Egreso de bancos
          {'filas':(23, 31),
            'nombre':'banco tipo',
            'columnas':(3, 8),
            'posx':36,
            'posy':558,
            'alinear':'I',
            'letra':'Ubuntu',
            'letra_alto':10,
            'desp_y':11,
            'desp_x':0,
          },
          {'filas':(23, 31),
            'nombre':'banco Descripcion',
            'columnas':(8, 39),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':72,
            'posy':558,
            'alinear':'I',
            'desp_y':11,
            'desp_x':0,
          },
          {'filas':(23, 31),
            'nombre':'banco / caja ',
            'columnas':(39, 46),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':342,
            'posy':558,
            'alinear':'C',
            'desp_y':11,
            'desp_x':0,
          },
          {'filas':(23, 31),
            'nombre':'banco Cpto_FE',
            'columnas':(46, 57),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':396,
            'posy':558,
            'alinear':'C',
            'desp_y':11,
            'desp_x':0,
          },
          {'filas':(23, 31),
            'nombre':'moneda',
            'columnas':(60, 63),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':442,
            'posy':558,
            'alinear':'C',
            'desp_y':11,
            'desp_x':0,
          },
          {'filas':(23, 31),
            'nombre':'egreso valor',
            'columnas':(63, 80),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':560,
            'posy':558,
            'alinear':'D',
            'desp_y':11,
            'desp_x':0,
          },
          { 'fila':36,
            'nombre':'egreso total',
            'columnas':(63, 80),
            'letra':'Ubuntu-Bold',
            'letra_alto':10,
            'posx':560,
            'posy':469.21,
            'alinear':'D',
            'desp_y':0,
            'desp_x':0,
          },
          { 'fila':40,
            'nombre':'cta',
            'columnas':(3, 5),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':50,
            'posy':425,
            'alinear':'C',
            'desp_y':0,
            'desp_x':0,
          },
          { 'fila':40,
            'nombre':'banco',
            'columnas':(5, 13),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':82,
            'posy':425,
            'alinear':'C',
            'desp_y':0,
            'desp_x':0,
          },
          { 'fila':40,
            'nombre':'nombre',
            'columnas':(13, 34),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':108,
            'posy':425,
            'alinear':'I',
            'desp_y':0,
            'desp_x':0,
          },
          { 'fila':40,
            'nombre':'Nro cuenta',
            'columnas':(34, 62),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':324,
            'posy':425,
            'alinear':'C',
            'desp_y':0,
            'desp_x':0,
          },
          { 'fila':40,
            'nombre':'titular',
            'columnas':(62, 80),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':490,
            'posy':425,
            'alinear':'C',
            'desp_y':0,
            'desp_x':0,
          },
          #Contabilizacion
          {'filas':(48, 80),
            'nombre':'cuenta',
            'columnas':(3, 12),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':37,
            'posy':400,
            'alinear':'I',
            'desp_y':11,
            'desp_x':0,
          },
          {'filas':(48, 80),
            'nombre':'oc',
            'columnas':(14, 17),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':126,
            'posy':400,
            'alinear':'C',
            'desp_y':11,
            'desp_x':0,
          },
          {'filas':(48, 80),
            'nombre':'terceros',
            'columnas':(20, 36),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':148,
            'posy':400,
            'alinear':'I',
            'desp_y':11,
            'desp_x':0,
          },
          {'filas':(48, 80),
            'nombre':'Dcto_Cruce/Provee.',
            'columnas':(38, 56),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':234,
            'posy':400,
            'alinear':'I',
            'desp_y':11,
            'desp_x':0,
          },
          {'filas':(48, 80),
            'nombre':'D e b i t o s ',
            'columnas':(57, 76),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':458,
            'posy':400,
            'alinear':'D',
            'desp_y':11,
            'desp_x':0,
          },
          {'filas':(48, 80),
            'nombre':'C r e d i t o s',
            'columnas':(77, 96),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':570,
            'posy':400,
            'alinear':'D',
            'desp_y':11,
            'desp_x':0,
          },
          #TOTALES
          { 'fila':44,
            'nombre':'Suma debitos',
            'columnas':(57, 76),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':458,
            'posy':76.9,
            'alinear':'D',
            'desp_y':0,
            'desp_x':0,
          },
          { 'fila':44,
            'nombre':'Suma creditos',
            'columnas':(77, 96),
            'letra':'Ubuntu',
            'letra_alto':10,
            'posx':570,
            'posy':76.9,
            'alinear':'D',
            'desp_y':0,
            'desp_x':0,
          },
          {'fila':46,
            'nombre':'elaborado por',
            'columnas':(13, 23),
            'letra':'Ubuntu',
            'letra_alto':9,
            'posx':310,
            'posy':13,
            'alinear':'I',
            'desp_y':0,
            'desp_x':0,
          },
          {'fila':47,
            'nombre':'Pagina numerador',
            'columnas':(1, 35),
            'letra':'Ubuntu',
            'letra_alto':9,
            'posx':468,
            'posy':700,
            'alinear':'I',
            'desp_y':0,
            'desp_x':0,
          },
          {'filas':(13, 18),
            'nombre':'Por Concepto de',
            'columnas':(20, 80),
            'letra':'Ubuntu',
            'letra_alto':7,
            'posx':37,
            'posy':70,
            'alinear':'I',
            'desp_y':11,
            'desp_x':0,
          },
]

archivo=open("comprobante.amb","wb")
pickle.dump(encabezado,archivo)
pickle.dump(selector,archivo)
archivo.close()
