#!/usr/bin/env python
# -*- coding: utf-8 -*-
import pickle
import datetime
#modelo Filas x Columnas
encabezado={
    "nombre":'retencion_dian',
    "tampapel":{'ancho': 8.5, 'alto': 11, 'medida': 'pul'},
    "pagup":{'up': (1, 1), 'uporden': 'Z'},
    "tipos":(('Ubuntu', 'Ubuntu-R.ttf'), ('Ubuntu-Bold', 'Ubuntu-B.ttf'),
             ('Ubuntu-Cond', 'Ubuntu-C.ttf'), ('f2sCodigo128', 'Codigo128.ttf')),
    "formato":'Formulario_220.png',#'Formulario_220_2021.pdf',
    "modo":1,
    "saltopag":('Nota:Este-Cert',),
    'anexarpdf':'Formulario_220_2021.pdf',
    # "saltolineadoc":1,
    "nombre_pdf":{'selector': [{'fila': 8, 'columnas': (57, 131)}, {'fila': 2, 'columnas': (53, 132)} ],
                  'formato': 'ret_dian-{}',
                  'ruta_pdf': '/home/www-data/web2py/applications/siendo/static/PDF'},
    "agrupar":{'fila': 8, 'columnas': (67, 80)},
    "correoweb2py":[{'fila': 8, 'columnas': (31, 55), 'nombre': 'nrodoc'},
                    {'fila': 8, 'columnas': (57, 131), 'nombre': 'nombre'},
                    {'fila': 8, 'columnas': (31, 55), 'nombre': 'nit', 'hasta': '-', 'borrar':','},
                    {'fila': 11, 'columnas': (53, 77), 'nombre': 'Fecha', 'convert': 'fecha6'},
                    {"fila":25, "columnas":(109,131),   "nombre":"valor","convert":"float"},
                ]
    }
selector=[
    { 'nombre':'Nit_cliente',
      'fila':4,
      'columnas':(7, 30),
      'letra':'Ubuntu-Bold',
      'letra_alto':10,
      'posx':36,
      'posy':689,
      'alinear':'I',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'Razon_Social',
      'fila':6,
      'columnas':(7, 60),
      'letra':'Ubuntu-Bold',
      'letra_alto':10,
      'posx':36,
      'posy':665,
      'alinear':'I',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'Nit',
      'fila':8,
      'columnas':(31, 55),
      'letra':'Ubuntu-Bold',
      'letra_alto':10,
      'posx':90,
      'posy':640,
      'alinear':'I',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'tipodoc',
      'fila':8,
      'columnas':(6, 29),
      'letra':'Ubuntu',
      'letra_alto':9,
      'posx':54,
      'posy':636,
      'alinear':'C',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'Nombre',
      'fila':8,
      'columnas':(57, 131),
      'letra':'Ubuntu-Bold',
      'letra_alto':10,
      'posx':234,
      'posy':640,
      'alinear':'I',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'fecha de año',
      'fila':11,
      'columnas':(10, 15),
      'letra':'Ubuntu',
      'letra_alto':9,
      'posx':68,
      'posy':621,
      'alinear':'C',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'fecha de mes',
      'fila':11,
      'columnas':(17, 21),
      'letra':'Ubuntu',
      'letra_alto':9,
      'posx':97,
      'posy':620,
      'alinear':'C',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'fecha de dia',
      'fila':11,
      'columnas':(23, 29),
      'letra':'Ubuntu',
      'letra_alto':9,
      'posx':120,
      'posy':620,
      'alinear':'C',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'fecha a año',
      'fila':11,
      'columnas':(35, 40),
      'letra':'Ubuntu',
      'letra_alto':9,
      'posx':180,
      'posy':621,
      'alinear':'C',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'fecha a mes',
      'fila':11,
      'columnas':(42, 45),
      'letra':'Ubuntu',
      'letra_alto':9,
      'posx':202,
      'posy':621,
      'alinear':'I',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'fecha a dia',
      'fila':11,
      'columnas':(47, 51),
      'letra':'Ubuntu',
      'letra_alto':9,
      'posx':226,
      'posy':621,
      'alinear':'I',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'fecha expedicion año',
      'fila':11,
      'columnas':(53, 60),
      'letra':'Ubuntu',
      'letra_alto':9,
      'posx':270,
      'posy':621,
      'alinear':'C',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'fecha expedicion mes',
      'fila':11,
      'columnas':(62, 69),
      'letra':'Ubuntu',
      'posx':300,
      'letra_alto':9,
      'posy':621,
      'alinear':'C',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'fecha expedicion dia',
      'fila':11,
      'columnas':(71, 77),
      'letra':'Ubuntu',
      'letra_alto':9,
      'posx':320,
      'posy':621,
      'alinear':'C',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'lugar retencion',
      'fila':11,
      'columnas':(79, 120),
      'letra':'Ubuntu',
      'letra_alto':10,
      'posx':342,
      'posy':618,
      'alinear':'I',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'dpto',
      'fila':11,
      'columnas':(122, 125),
      'letra':'Ubuntu',
      'letra_alto':9,
      'posx':522,
      'posy':615,
      'alinear':'I',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'ciu-munp',
      'fila':11,
      'columnas':(127, 131),
      'letra':'Ubuntu',
      'letra_alto':9,
      'posx':550,
      'posy':615,
      'alinear':'I',
      'desp_y':0,
      'desp_x':0,
    },
    { 'nombre':'36-48 COLS',
      'filas':(13,25),
      'columnas':(109, 131),
      'letra':'Ubuntu',
      'letra_alto':10,
      'posx':580,
      'posy':590,
      'alinear':'D',
      'desp_y':12,
      'desp_x':0,
    },
    { 'nombre':'49-56 COLS',
      'filas':(27,34),
      'columnas':(109, 131),
      'letra':'Ubuntu',
      'letra_alto':10,
      'posx':580,
      'posy':422,
      'alinear':'D',
      'desp_y':11.8,
      'desp_x':0,
    },
    { 'nombre':'64-71 COLS',
      'filas':(39,46),
      'columnas':(114, 131),
      'letra':'Ubuntu',
      'letra_alto':10,
      'posx':580,
      'posy':290,
      'alinear':'D',
      'desp_y':11.8,
      'desp_x':0,
    },
    { 'nombre':'57-63 COLS',
    'columnas':(91, 107),
      'filas':(39,46),
      'letra':'Ubuntu',
      'letra_alto':10,
      'posx':455,
      'posy':290,
      'alinear':'D',
      'desp_y':11.8,
      'desp_x':0,
    },
    { 'nombre':'74 COLS',
    'columnas':(114, 131),
      'fila':48,
      'letra':'Ubuntu',
      'letra_alto':10,
      'posx':580,
      'posy':110,
      'alinear':'D',
      'desp_y':11.8,
      'desp_x':0,
    },
    { 'nombre':'firma',
    'columnas':(104, 131),
      'fila':58,
      'letra':'Ubuntu',
      'letra_alto':10,
      'posx':504,
      'posy':30,
      'alinear':'C',
      'desp_y':11.8,
      'desp_x':0,
    },



]

archivo=open("retencion_dian.amb","wb")
pickle.dump(encabezado,archivo)
pickle.dump(selector,archivo)
archivo.close()
