#!/usr/bin/env python
# -*- coding: utf-8 -*-
import pickle
ambiente={
    "nombre":"RetencionAnual",
    "tampapel":{"ancho":8.5,"alto":5.5,"medida":"pul"},
    "pagup":{"up":(1,1), "uporden":"Z"},						# si esta activo se define la paginas logicas  [col], [Filas] y el orden "Z" or "W"
    "tipos":( ('Ubuntu',     'Ubuntu-R.ttf'), 					# (nombre logico, nombre fisico)  Nota debe estar en fonts
    		  ('Ubuntu-Bold','Ubuntu-B.ttf'),
    		  ('Ubuntu-Cond','Ubuntu-C.ttf'),
    		  ('f2sCodigo128','Codigo128.ttf')					# Si se va a usar codigo de barras se debe colocar....!
    		),
    "formato":"retencion_anual.png",
    'pag_despx':0,                                              #Mueve el formato  con respecto  a los datos.
    'pag_despy':0,
    "modo":5,                                                   # Lectura PDF
    "limite_total":{'texto':'TOTAL', 'y0':-4, 'y1':4},         #texto para extraer limite en y=-2 y1=+2
    "buscador_texto":[{'texto':'Fecha de expedición:','campo':'fecha','ofsety0':20,'ofsety1':20},
                      {'texto':'Valor:','campo':'valor_letras','ofsety0':20,'ofsety1':20},
                     ], #Resignar el area limite y0, y1
    'idpag':'{nrodoc}',
    'web2pycampos':[
                     'nrodoc',
                     'F2S_LoadPlugins.call_plugin("ExtraerDatos", texto=self.obPagina.campos["nit"]["texto"], indice=0, separador="-")',
                     'F2S_LoadPlugins.call_plugin("ModNomCliente", entregadoa=self.obPagina.campos["retenidoa"]["texto"])',
                     'F2S_LoadPlugins.call_plugin("ModFecha1", fecha=self.obPagina.campos["fecha"]["texto"])',
                     'F2S_LoadPlugins.call_plugin("ModValorTotal", valor_total=self.obPagina.campos["total_vr_retenido"]["texto"])',
                     'nombrepdf'
                     ],
    'funciones':['F2S_LoadPlugins.call_plugin("DcoCompuesto", objPagina=self.obPagina, ruta="Retencion_Anual" )'],    #Genera el nombre del pdf y nrodoc
    #Mejoras:
    #Esto hay crear otra variable, para dividir encabazado de seleccion....!!!!
    'bloques':[
        {   #titulo
            'x0': 127.0,  'x1': 478.5,
            'y0': 671.5,  'y1': 672.0,
            'selectores':[
                        {'nombre':'titulo',
                            'fila':1,
                            'cols':(1,80),
                            'letra':'Ubuntu-Bold',
                            'letra_alto':10,
                            'posx':420,
                            'posy':340,
                            'alinear':'C',
                            'desp_y':0,
                            'desp_x':0,
                            'colortexto_rgb':(0,0,128),
                            'texto': []},
                        ],
        },
        {   #Rango de Fecha periodo
            'x0': 207.0,  'x1': 405.0,
            'y0': 658.0,  'y1': 658.5,
            'selectores':[
                {'nombre':'rango_fecha',
                    'fila':1,
                    'cols':(1,80),
                    'letra':'Ubuntu-Bold',
                    'letra_alto':8,
                    'posx':420,
                    'posy':330,
                    'alinear':'C',
                    'desp_y':0,
                    'desp_x':0,
                    'texto': []},
            ],
        },
        {   #Retenido a
            'x0':   21.0,  'x1':  500.0,
            'y0':  605.0,  'y1':  605.5,
            'selectores':[
                {'nombre':'retenidoa',
                'fila':1,
                'cols':(1,90),
                'letra':'Ubuntu-Bold',
                'letra_alto':9,
                'posx':100,
                'posy':254,
                'alinear':'I',
                'desp_y':0,
                'desp_x':0,
                'texto': []},
            ],
        },
        {   #Nit
            'x0': 21.0,  'x1':  300.0,
            'y0': 593.0,  'y1': 593.5,
            'selectores':[
                {'nombre':'nit',
                    'fila':1,
                    'cols':(4,90),
                    'letra':'Ubuntu-Bold',
                    'letra_alto':9,
                    'posx':80,
                    'posy':268,
                    'alinear':'I',
                    'desp_y':0,
                    'desp_x':0,
                    'texto': []},
                ],
        },
        {   #Direccion
            'x0': 109.5,  'x1': 800.0,
            'y0': 576.5,  'y1': 577.0,
            'selectores':[
                {'nombre':'direccion',
                    'fila':1,
                    'cols':(1,90),
                    'letra':'Ubuntu',
                    'letra_alto':9,
                    'posx':105,
                    'posy':240,
                    'alinear':'I',
                    'desp_y':0,
                    'desp_x':300,
                    'texto': []},
                ],
        },
        {   #Ciudad
            'x0': 109.5,  'x1': 500.0,
            'y0': 566.5,  'y1': 567.0,

            'selectores':[
                {'nombre':'direccion',
                    'fila':1,
                    'cols':(1,90),
                    'letra':'Ubuntu',
                    'letra_alto':9,
                    'posx':407,
                    'posy':240,
                    'alinear':'I',
                    'desp_y':0,
                    'desp_x':0,
                    'texto': []},
                ],
        },
        {   #Ciudad donde practico retención
            'x0': 262.5,  'x1':  800.0,
            'y0': 534.5,  'y1': 535.00004,
            'selectores':[
                {'nombre':'ciudad_pract',
                    'fila':1,
                    'cols':(1,90),
                    'letra':'Ubuntu',
                    'letra_alto':9,
                    'posx':230,
                    'posy':227,
                    'alinear':'I',
                    'desp_y':0,
                    'desp_x':0,
                    'texto': []},
                ],
        },
        {   #Ciudad donde se consignó la retención
            'x0': 262.5,  'x1':  800.0,
            'y0': 521.0,  'y1': 521.50004,
            'selectores':[
                {'nombre':'ciudad_cons',
                    'fila':1,
                    'cols':(1,90),
                    'letra':'Ubuntu',
                    'letra_alto':9,
                    'posx':230,
                    'posy':213,
                    'alinear':'I',
                    'desp_y':0,
                    'desp_x':0,
                    'texto': []},
                ],
        },
        #Detalle iva retenido
        {   #concepto
            'x0':  21.0,  'x1':  300.0,
            'y0': 412.0,  'y1': 463.0,
            'detalle':True,
            'selectores':[
                {'nombre':'concepto_tasa',
                    'fila':1,
                    'cols':(1,90),
                    'letra':'Ubuntu',
                    'letra_alto':9,
                    'posx':55,
                    'posy':165,
                    'alinear':'I',
                    'desp_y':11,
                    'desp_x':0,
                    'texto': []},
                ],
        },
        {   #tasa
            'x0': 297.0,  'x1': 317.0,
            'y0': 412.0,  'y1': 463.0,

            'detalle':True,                     #se ve afectado por el total
            'selectores':[
                {'nombre':'tasa',
                    'fila':1,
                    'cols':(1,90),
                    'letra':'Ubuntu',
                    'letra_alto':9,
                    'posx':310,
                    'posy':154,
                    'alinear':'I',
                    'desp_y':22,
                    'desp_x':0,
                    'texto': []},
                ],
        },
        {   #col Valor Base
            'x0': 340.0 ,  'x1': 453.5,
            'y0': 412.0,  'y1': 463.0,
            'detalle':True,                     #se ve afectado por el total
            'selectores':[{'nombre':'vr_base',
                        'fila':1,
                        'cols':(1,90),
                        'letra':'Ubuntu',
                        'letra_alto':9,
                        'posx':435,
                        'posy':154,
                        'alinear':'D',
                        'desp_y':22,
                        'desp_x':0,
                        'texto': []},
                    ],
        },
        {   #col vr Retenido
            'x0': 500.0,  'x1':590.5,
            'y0': 412.0,  'y1': 463.0,
            'detalle':True,                     #se ve afectado por el total
            'selectores':[{'nombre':'col_vr_retenido',
                            'fila':1,
                            'cols':(1,90),
                            'letra':'Ubuntu',
                            'letra_alto':9,
                            'posx':540,
                            'posy':154,
                            'alinear':'D',
                            'desp_y':22,
                            'desp_x':0,
                            'texto': []},
                        ],
        },
        #totales
        {   #Valor letras
            'x0':                72.5,  'x1':               450.0,
            'y0':               357.5,  'y1':               358.0,
            'reubicar':'valor_letras',
            'selectores':[{'nombre':'valor_letras',
                        'fila':1,
                        'cols':(1,90),
                        'letra':'Ubuntu',
                        'letra_alto':7,
                        'posx':55,
                        'posy':70,
                        'alinear':'I',
                        'desp_y':10,
                        'desp_x':0,
                        'texto': []},
                    ],
        },
        {   #total vr base
            'x0':               340.0,  'x1':               453.5,
            'y0':               394.0,  'y1':               410.0,
            'total':True,        #Indicador para campo total
            'selectores':[{'nombre':'total_vr_base',
                        'fila':1,
                        'cols':(1,90),
                        'letra':'Ubuntu-Bold',
                        'letra_alto':9,
                        'posx':435,
                        'posy':68,
                        'alinear':'D',
                        'desp_y':0,
                        'desp_x':0,
                        'texto': []},
                    ],
        },
        {   #total vr retenido
        'x0':               500.0,  'x1':               590.5,
        'y0':               394.0,  'y1':               395.0,
        'total':True,        #Indicador para campo total
        'selectores':[{'nombre':'total_vr_retenido',
            'fila':1,
            'cols':(1,90),
            'letra':'Ubuntu-Bold',
            'letra_alto':9,
            'posx':540,
            'posy':68,
            'alinear':'D',
            'desp_y':0,
            'desp_x':0,
            'texto': []},
            ],
        },
        #Generales
        {   #fecha +
        'x0':               148.0,  'x1':               208.0,
        'y0':               260.5,  'y1':               261.0,
        'reubicar':'fecha',
        'selectores':[{'nombre':'fecha',
            'fila':1,
            'cols':(1,90),
            'letra':'Ubuntu',
            'letra_alto':8,
            'posx':460,
            'posy':295,
            'alinear':'I',
            'desp_y':0,
            'desp_x':0,
            'texto': []},
            ],
        },


    ]
}

opcional=False

archivo=open("retencionanual_enterprice.amb","wb")
pickle.dump(ambiente,archivo)
archivo.close()
